# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'displayform.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(805, 543)
        MainWindow.setMaximumSize(QtCore.QSize(1280, 1024))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.matplotlibwidget = MatplotlibWidget(self.centralwidget)
        self.matplotlibwidget.setGeometry(QtCore.QRect(200, 0, 601, 491))
        self.matplotlibwidget.setObjectName("matplotlibwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 390, 171, 61))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.lblShowTime = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblShowTime.setText("")
        self.lblShowTime.setObjectName("lblShowTime")
        self.gridLayout.addWidget(self.lblShowTime, 1, 1, 1, 1)
        self.lblShowDate = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblShowDate.setText("")
        self.lblShowDate.setObjectName("lblShowDate")
        self.gridLayout.addWidget(self.lblShowDate, 0, 1, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 280, 111, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnStart = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnStart.setObjectName("btnStart")
        self.verticalLayout.addWidget(self.btnStart)
        self.btnStop = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnStop.setObjectName("btnStop")
        self.verticalLayout.addWidget(self.btnStop)
        self.btnReset = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnReset.setObjectName("btnReset")
        self.verticalLayout.addWidget(self.btnReset)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 174, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.cbxSelectFunction = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.cbxSelectFunction.setObjectName("cbxSelectFunction")
        self.cbxSelectFunction.addItem("")
        self.cbxSelectFunction.addItem("")
        self.horizontalLayout.addWidget(self.cbxSelectFunction)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 90, 191, 181))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(10, 10, 72, 15))
        self.label.setObjectName("label")
        self.starttimehour = QtWidgets.QSpinBox(self.page)
        self.starttimehour.setGeometry(QtCore.QRect(10, 30, 46, 22))
        self.starttimehour.setMaximum(23)
        self.starttimehour.setObjectName("starttimehour")
        self.starttimeminute = QtWidgets.QSpinBox(self.page)
        self.starttimeminute.setGeometry(QtCore.QRect(70, 30, 46, 22))
        self.starttimeminute.setMaximum(59)
        self.starttimeminute.setObjectName("starttimeminute")
        self.starttimesecond = QtWidgets.QSpinBox(self.page)
        self.starttimesecond.setGeometry(QtCore.QRect(130, 30, 46, 22))
        self.starttimesecond.setMaximum(59)
        self.starttimesecond.setObjectName("starttimesecond")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 72, 15))
        self.label_2.setObjectName("label_2")
        self.endtimehour = QtWidgets.QSpinBox(self.page)
        self.endtimehour.setGeometry(QtCore.QRect(10, 80, 46, 22))
        self.endtimehour.setMaximum(23)
        self.endtimehour.setObjectName("endtimehour")
        self.endtimeminute = QtWidgets.QSpinBox(self.page)
        self.endtimeminute.setGeometry(QtCore.QRect(70, 80, 46, 22))
        self.endtimeminute.setMaximum(59)
        self.endtimeminute.setObjectName("endtimeminute")
        self.endtimesecond = QtWidgets.QSpinBox(self.page)
        self.endtimesecond.setGeometry(QtCore.QRect(130, 80, 46, 22))
        self.endtimesecond.setMaximum(59)
        self.endtimesecond.setObjectName("endtimesecond")
        self.label_5 = QtWidgets.QLabel(self.page)
        self.label_5.setGeometry(QtCore.QRect(10, 120, 72, 15))
        self.label_5.setObjectName("label_5")
        self.sbxdrawspeed = QtWidgets.QSpinBox(self.page)
        self.sbxdrawspeed.setGeometry(QtCore.QRect(90, 120, 46, 22))
        self.sbxdrawspeed.setMinimum(10)
        self.sbxdrawspeed.setMaximum(100)
        self.sbxdrawspeed.setObjectName("sbxdrawspeed")
        self.btnOpenFile = QtWidgets.QPushButton(self.page)
        self.btnOpenFile.setGeometry(QtCore.QRect(40, 150, 111, 28))
        self.btnOpenFile.setObjectName("btnOpenFile")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.page_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 50, 191, 95))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 1, 1, 1)
        self.cbxCarColor2 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.cbxCarColor2.setObjectName("cbxCarColor2")
        self.cbxCarColor2.addItem("")
        self.cbxCarColor2.addItem("")
        self.cbxCarColor2.addItem("")
        self.cbxCarColor2.addItem("")
        self.cbxCarColor2.addItem("")
        self.cbxCarColor2.addItem("")
        self.gridLayout_2.addWidget(self.cbxCarColor2, 2, 1, 1, 1)
        self.cbxCarColor1 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.cbxCarColor1.setObjectName("cbxCarColor1")
        self.cbxCarColor1.addItem("")
        self.cbxCarColor1.addItem("")
        self.cbxCarColor1.addItem("")
        self.cbxCarColor1.addItem("")
        self.cbxCarColor1.addItem("")
        self.cbxCarColor1.addItem("")
        self.gridLayout_2.addWidget(self.cbxCarColor1, 1, 1, 1, 1)
        self.chbxCar2 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.chbxCar2.setObjectName("chbxCar2")
        self.gridLayout_2.addWidget(self.chbxCar2, 2, 0, 1, 1)
        self.chbxCar1 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.chbxCar1.setObjectName("chbxCar1")
        self.gridLayout_2.addWidget(self.chbxCar1, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 460, 81, 24))
        self.label_6.setObjectName("label_6")
        self.lblStarNums1 = QtWidgets.QLabel(self.centralwidget)
        self.lblStarNums1.setGeometry(QtCore.QRect(90, 460, 31, 24))
        self.lblStarNums1.setText("")
        self.lblStarNums1.setObjectName("lblStarNums1")
        self.lblStarNums2 = QtWidgets.QLabel(self.centralwidget)
        self.lblStarNums2.setGeometry(QtCore.QRect(150, 460, 31, 24))
        self.lblStarNums2.setText("")
        self.lblStarNums2.setObjectName("lblStarNums2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 805, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.cbxCarColor2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "时间："))
        self.label_3.setText(_translate("MainWindow", "日期："))
        self.btnStart.setText(_translate("MainWindow", "开始"))
        self.btnStop.setText(_translate("MainWindow", "暂停"))
        self.btnReset.setText(_translate("MainWindow", "重置"))
        self.label_7.setText(_translate("MainWindow", "功能选择："))
        self.cbxSelectFunction.setItemText(0, _translate("MainWindow", "文件读取"))
        self.cbxSelectFunction.setItemText(1, _translate("MainWindow", "实时轨迹"))
        self.label.setText(_translate("MainWindow", "开始时间:"))
        self.label_2.setText(_translate("MainWindow", "结束时间:"))
        self.label_5.setText(_translate("MainWindow", "画图速度："))
        self.btnOpenFile.setText(_translate("MainWindow", "打开文件"))
        self.label_9.setText(_translate("MainWindow", "选择颜色"))
        self.cbxCarColor2.setItemText(0, _translate("MainWindow", "红"))
        self.cbxCarColor2.setItemText(1, _translate("MainWindow", "黄"))
        self.cbxCarColor2.setItemText(2, _translate("MainWindow", "蓝"))
        self.cbxCarColor2.setItemText(3, _translate("MainWindow", "绿"))
        self.cbxCarColor2.setItemText(4, _translate("MainWindow", "紫"))
        self.cbxCarColor2.setItemText(5, _translate("MainWindow", "白"))
        self.cbxCarColor1.setItemText(0, _translate("MainWindow", "红"))
        self.cbxCarColor1.setItemText(1, _translate("MainWindow", "黄"))
        self.cbxCarColor1.setItemText(2, _translate("MainWindow", "蓝"))
        self.cbxCarColor1.setItemText(3, _translate("MainWindow", "绿"))
        self.cbxCarColor1.setItemText(4, _translate("MainWindow", "紫"))
        self.cbxCarColor1.setItemText(5, _translate("MainWindow", "白"))
        self.chbxCar2.setText(_translate("MainWindow", "苏B-A5339"))
        self.chbxCar1.setText(_translate("MainWindow", "苏B-A2345"))
        self.label_8.setText(_translate("MainWindow", "选择车辆"))
        self.label_6.setText(_translate("MainWindow", "卫星个数："))

from matplotlibwidget import MatplotlibWidget
